### ISSUE TITLE
Fjerne didgisos tilpassninger i dittnav-api (og FE?)

### ISSUE THREAD

**Issue by rannveigskjerve** [navikt/dittnav-api#167]
Pilot hos digisos med brukernotifikasjoner er avslutta, da har vi en del kode som kan fjernes:

Muligens tre Digisos-varianter vi har : 
- Brukernotifikasjon (beskjed) for meldinger. Det er denne de har kuttet ut nå.
- "Fake" brukernotifikasjoner (for søknader?)?
- Spesialhåndtering i Mine saker /Dine siste saker (Min side) for sakstema /saker - har ikke noe med brukernotifikasjoner å gjøre

**Comment by ToneEriksen** [comment]
Mulig det ikke er så mye vi må gjøre nå? Det de har kuttet ut er "ekte" brukernotifikasjon (beskjed) for meldinger i ett pilotkontor. Det betyr vel for oss bare at de slutter å produsere. Evt at de kan fjernes som produsent?

De andre to Digisos-variantene skal ikke fjernes:
- "Fake" brukernotifikasjoner for påbegynte søknader. Skal beholdes.
- Spesialhåndtering i Mine saker /Dine siste saker (Min side) for sakstema /saker - har ikke noe med brukernotifikasjoner å gjøre. Skal beholdes.
